logging:
  level:
    root: info
    web: info
    sql: info
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS,UTC
spring:
#  profiles:
#    active: ${PROFILE:local}
  lifecycle:
    timeout-per-shutdown-phase: 30s
  application:
    name: demo
  jpa:
    database: h2
    open-in-view: false
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  sleuth:
    trace-id128: true
  liquibase:
    enabled: false
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    
springdoc:
  show-actuator: true
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    try-it-out-enabled: false

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    java:
      enabled: true
      
server:
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 2KB
  port: 8080
  shutdown: graceful

info:
  message: hello
  
  
  
  