logging:
  level:
    root: info
    web: info
    sql: info
spring:
#  profiles:
#    active: ${PROFILE:local}
  lifecycle:
    timeout-per-shutdown-phase: 30s
  application:
    name: demo
  jpa:
    open-in-view: false
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  sleuth:
    trace-id128: true
    

springdoc:
  show-actuator: true
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    try-it-out-enabled: true

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    java:
      enabled: true
      
server:
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 2KB
  port: 8080
  shutdown: graceful

info:
  message: hello
  